version: "3.9"

services:
    app:
        build: .
        networks:
            discord-bot:
                aliases:
                    - frontend

networks:
    discord-bot:
        external: true